version: "3.8"

services:
  api:
    build: ./SnappTrip
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    volumes:
      - ./SnappTrip:/app
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - database:/var/opt/mssql

volumes:
  database: