version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./SnappTrip/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    volumes:
      - ./SnappTrip:/src
    restart: unless-stopped
  #db:
  #  image: "mcr.microsoft.com/mssql/server"
  #  environment:
  #    SA_PASSWORD: "Your_password123"
  #    MSSQL_SA_PASSWORD: "Your_password123"
  #    ACCEPT_EULA: "Y"
  #  ports:
  #    - 1433:1433
  #  volumes:
  #    - database:/var/opt/mssql
  #  restart: unless-stopped
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Your_password123
      - POSTGRES_DB=SnappTripDB
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  database: