version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./SnappTrip/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    volumes:
      - ./SnappTrip:/src
    restart: unless-stopped
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - database:/var/opt/mssql
    restart: unless-stopped

volumes:
  database: